---
# This is the Github action code used for CI runs
name: 'Check for invalid syntax'
author: "Zack Smith"
description: 'Ensure code blocks syntax is correct'
inputs:
  profile:
    description: 'The profile to run'
    required: false
    default: 'all'
outputs:
  inspec-output:
    description: 'The output of inspec'
runs:
  using: 'docker'
  image: 'dind/Dockerfile'
  env:
    PROFILE: ${{ inputs.profile }}
  entrypoint: "/usr/local/bin/docker-compose"
  args:
    - "up"
    - "--file"
    - "/gitub/workspace/docker-compose.yml"
branding:
  color: "black"
  icon: "dollar-sign"
