---
# This is the Github action code used for CI runs
name: 'Check markdown codeblocks'
author: "Zack Smith"
description: 'Run inspec against markdown'
inputs:
  profile:
    description: 'The profile to run'
    required: false
    default: 'all'
  markdown:
    description: 'The directory containing the markdown'
    required: true
  github_token:
    description: 'Github token used by github profile'
    required: true
outputs:
  inspec-output:
    description: 'The output of inspec'
runs:
  using: 'docker'
  image: 'docker://acidprime/inspec' 
  env:
    MARKDOWN: ${{ inputs.markdown }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
  args:
    - 'exec'
    - /profiles/${{ inputs.profile }}
    - '--target=docker://inspec-target'
    - '--reporter'
    - 'cli'
    - 'html:inspec.html'
    - '--log-level=debug'
    - '--show-progress'
    - '--no-color'
branding:
  color: "black"
  icon: "dollar-sign"
