---
# This is the Github action code used for CI runs
name: 'Check for invalid syntax'
author: "Zack Smith"
description: 'Ensure code blocks syntax is correct'
inputs:
  profile:
    description: 'The profile to run'
    required: false
    default: 'all'
  markdown:
    description: 'The directory containing the markdown'
    required: true
outputs:
  inspec-output:
    description: 'The output of inspec'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PROFILE: ${{ inputs.profile }}
    MARKDOWN: ${{ inputs.markdown }}
  entrypoint: "/usr/local/bin/docker-compose"
  args:
    - "--file"
    - "/stack/docker-compose.yml"
    - "--log-level"
    - "DEBUG"
    - "up"
    - "--exit-code-from"
    - "inspec"
branding:
  color: "black"
  icon: "dollar-sign"
