# This compose file is used for Github Actions 
version: '3'
services:
  inspec-target:
    container_name: "inspec-target"
    build: ./target
  inspec:
    container_name: "inspec"
    context: .
    dockerfile: Dockerfile.inspec
    volumes:
      - /github/workspace:/markdown
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - 'exec'
      - 'profiles/${PROFILE:?}'
      - '--target=docker://inspec-target'
      - '--reporter cli'
      - '--log-level=debug'
      - '--show-progress'
