# This compose file is used for Github Actions 
version: '3'
services:
  inspec-target:
    container_name: "inspec-target"
    build: ./target
  inspec:
    container_name: "inspec"
    depends_on:
      - "inspec-target"
    build:
      context: .
      dockerfile: Dockerfile.inspec
    volumes:
      - markdown:/markdown
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - 'exec'
      - 'profiles/${PROFILE:?}'
      - '--target=docker://inspec-target'
      - '--reporter'
      - 'cli'
      - '--log-level=debug'
      - '--show-progress'
volumes:
  markdown:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MARKDOWN:?Markdown Directory Missing} 
